/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fat.GUI.Dialogs.Categories;
import com.fat.BUS.Services.CategoryService;
import com.fat.DTO.Categories.CategoryViewDTO;
import com.fat.DTO.Categories.CreateOrUpdateCategoryDTO;
import javax.swing.JOptionPane;
/**
 *
 * @author GIGABYTE
 */
public class AddOrUpdateCategoryDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddOrUpdateCategoryDialog.class.getName());

    private final CategoryService categoryService;
    private final CategoryViewDTO existingCategory; // null = THÊM MỚI, not null = SỬA
    /**
     * Creates new form AddOrUpdateCategoryDialog
     */
    public AddOrUpdateCategoryDialog(java.awt.Frame parent, boolean modal, CategoryViewDTO existingCategory) {
    super(parent, modal);
    this.categoryService = CategoryService.getInstance();
    this.existingCategory = existingCategory;
    initComponents();
    setupDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý danh mục");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Thêm Danh Mục");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, 20));

        txtName.setToolTipText("Tên danh mục");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 140, 140, -1));

        btnSave.setText("Lưu");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(this::btnSaveActionPerformed);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        btnCancel.setText("Thoát");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Tên danh mục không được để trống", 
                "Lỗi nhập liệu", 
                JOptionPane.ERROR_MESSAGE);
            txtName.requestFocus();
            return;
        }
        CreateOrUpdateCategoryDTO dto;
        if(existingCategory != null){
            //sửa
            dto = new CreateOrUpdateCategoryDTO(existingCategory.getId(), name);
        }else{
            //thêm
            dto = new CreateOrUpdateCategoryDTO(name);
        }
        try{
            if(existingCategory != null){
                //sửa
                categoryService.updateCategory(dto);
                JOptionPane.showMessageDialog((this), 
                "Cập nhật danh mục thành công", 
                "Thành công", 
                JOptionPane.INFORMATION_MESSAGE);
            }else{
                // THÊM
            categoryService.createCategory(dto);
            JOptionPane.showMessageDialog(this,
            "Thêm danh mục thành công!",
            "Thành công",
            JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Lỗi",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    //         logger.log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the dialog */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         @Override
    //         public void run() {
    //             AddOrUpdateCategoryDialog dialog = new AddOrUpdateCategoryDialog(new javax.swing.JFrame(), true);
    //             dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                 @Override
    //                 public void windowClosing(java.awt.event.WindowEvent e) {
    //                     System.exit(0);
    //                 }
    //             });
    //             dialog.setVisible(true);
    //         }
    //     });
    // }


    private void setupDialog(){
        if(existingCategory != null){
            //sửa
            lblTitle.setText("Sửa Danh Mục");
            txtName.setText(existingCategory.getName());
        }else{
            //thêm
            lblTitle.setText("Thêm Danh Mục");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
