// ===================================================================
// CODE HOÀN CHỈNH CHO AddOrUpdateStaffDialog.java
// Copy code này THAY THẾ phần code hiện tại trong AddOrUpdateStaffDialog.java
// (Giữ nguyên phần initComponents() được generate bởi NetBeans)
// ===================================================================

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fat.GUI.Dialogs.Staffs;

import com.fat.BUS.Abstractions.Services.IRoleService;
import com.fat.BUS.Abstractions.Services.IStaffService;
import com.fat.BUS.Services.RoleService;
import com.fat.BUS.Services.StaffService;
import com.fat.BUS.Utils.ValidatorUtil;
import com.fat.Contract.Exceptions.ValidationException;
import com.fat.DTO.Roles.RoleViewDTO;
import com.fat.DTO.Staffs.CreateOrUpdateStaffDTO;
import com.fat.DTO.Staffs.StaffDetailDTO;
import com.formdev.flatlaf.FlatClientProperties;
import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author GIGABYTE
 */
public class AddOrUpdateStaffDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddOrUpdateStaffDialog.class.getName());
    private IStaffService staffService = StaffService.getInstance();
    private IRoleService roleService = RoleService.getInstance();
    private StaffDetailDTO staffDetailDTO = null;
    private boolean isConfirmed = false;

    /**
     * Creates new form AddOrUpdateStaffDialog
     */
    public AddOrUpdateStaffDialog(java.awt.Frame parent, boolean modal, StaffDetailDTO staffDetailDTO) {
        super(parent, modal);
        this.staffDetailDTO = staffDetailDTO;
        initComponents();
        loadRoles();
        setCss();
        initStaffDetail();
    }

    private void loadRoles() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboRole.getModel();
        var roles = roleService.getAllRoles();

        for (var role : roles) {
            model.addElement(role);
        }
        
        if (model.getSize() > 0) {
            cboRole.setSelectedIndex(0);
        }
    }

    private void setCss() {
        btnSave1.putClientProperty(FlatClientProperties.STYLE, "arc: 10; borderWidth: 0;");
        txtFirstName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên");
        txtLastName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập họ");
        txtPhoneNumber.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập số điện thoại");
        txtUserName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên đăng nhập");
        txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mật khẩu (ít nhất 6 ký tự)");
        txtSalary.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mức lương");
    }

    private void initStaffDetail() {
        if (staffDetailDTO != null) {
            setTitle("Cập nhật thông tin nhân viên");
            
            txtFirstName.setText(staffDetailDTO.getFirstName());
            txtLastName.setText(staffDetailDTO.getLastName());
            txtPhoneNumber.setText(staffDetailDTO.getPhoneNumber());
            txtUserName.setText(staffDetailDTO.getUserName());
            txtSalary.setText(staffDetailDTO.getSalary().toString());
            
            // Set ngày sinh
            if (staffDetailDTO.getBirthDate() != null) {
                Date birthDate = Date.from(staffDetailDTO.getBirthDate()
                        .atStartOfDay(ZoneId.systemDefault()).toInstant());
                dateChooserBirthDate.setDate(birthDate);
            }
            
            // Chọn vai trò tương ứng
            for (int i = 0; i < cboRole.getItemCount(); i++) {
                RoleViewDTO role = (RoleViewDTO) cboRole.getItemAt(i);
                if (role.getId().equals(staffDetailDTO.getRoleId())) {
                    cboRole.setSelectedIndex(i);
                    break;
                }
            }
            
            // Khi update, password là tùy chọn
            txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, 
                    "Để trống nếu không đổi mật khẩu");
        } else {
            setTitle("Thêm nhân viên mới");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: DO NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // ===================================================================
        // PHẦN NÀY ĐƯỢC GENERATE TỰ ĐỘNG BỞI NETBEANS
        // GIỮ NGUYÊN CODE HIỆN CÓ TRONG FILE CỦA BẠN
        // KHÔNG COPY PHẦN NÀY
        // ===================================================================
        
        // Đảm bảo các components sau có trong form của bạn:
        // - txtFirstName (JTextField)
        // - txtLastName (JTextField)
        // - txtPhoneNumber (JTextField)
        // - txtUserName (JTextField)
        // - txtPassword (JPasswordField)
        // - txtSalary (JTextField)
        // - dateChooserBirthDate (JDateChooser từ thư viện JCalendar)
        // - cboRole (JComboBox)
        // - btnSave1 (JButton)
        
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseClicked
        try {
            // Lấy dữ liệu từ form
            String firstName = txtFirstName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String phoneNumber = txtPhoneNumber.getText().trim();
            String userName = txtUserName.getText().trim();
            String password = new String(txtPassword.getPassword()).trim();
            String salaryText = txtSalary.getText().trim();
            
            // Validate cơ bản
            if (firstName.isEmpty()) {
                throw new ValidationException("Tên nhân viên không được để trống");
            }
            
            if (phoneNumber.isEmpty()) {
                throw new ValidationException("Số điện thoại không được để trống");
            }
            
            if (userName.isEmpty()) {
                throw new ValidationException("Tên đăng nhập không được để trống");
            }
            
            // Validate password
            if (staffDetailDTO == null && password.isEmpty()) {
                throw new ValidationException("Mật khẩu không được để trống");
            }
            
            if (!password.isEmpty() && password.length() < 6) {
                throw new ValidationException("Mật khẩu phải có ít nhất 6 ký tự");
            }
            
            // Parse salary
            BigDecimal salary = null;
            if (!salaryText.isEmpty()) {
                try {
                    salary = new BigDecimal(salaryText);
                    if (salary.compareTo(BigDecimal.ZERO) < 0) {
                        throw new ValidationException("Mức lương phải lớn hơn 0");
                    }
                } catch (NumberFormatException e) {
                    throw new ValidationException("Mức lương không hợp lệ");
                }
            } else {
                throw new ValidationException("Mức lương không được để trống");
            }
            
            // Lấy ngày sinh
            Date birthDateFromChooser = dateChooserBirthDate.getDate();
            LocalDate birthDate = null;
            if (birthDateFromChooser != null) {
                birthDate = birthDateFromChooser.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
            } else {
                throw new ValidationException("Ngày sinh không được để trống");
            }
            
            // Lấy role
            RoleViewDTO selectedRole = (RoleViewDTO) cboRole.getSelectedItem();
            if (selectedRole == null) {
                throw new ValidationException("Vui lòng chọn vai trò");
            }
            Integer roleId = selectedRole.getId();
            
            // Xử lý CREATE hoặc UPDATE
            if (staffDetailDTO == null) {
                // CREATE
                CreateOrUpdateStaffDTO newStaff = new CreateOrUpdateStaffDTO(
                        firstName,
                        lastName,
                        birthDate,
                        salary,
                        phoneNumber,
                        userName,
                        password,
                        roleId
                );
                
                staffService.createStaff(newStaff);
                JOptionPane.showMessageDialog(this,
                        "Thêm nhân viên thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                // UPDATE
                CreateOrUpdateStaffDTO updateStaff = new CreateOrUpdateStaffDTO(
                        staffDetailDTO.getId(),
                        firstName,
                        lastName,
                        birthDate,
                        phoneNumber,
                        salary,
                        java.time.LocalDateTime.now(),
                        userName,
                        roleId,
                        password.isEmpty() ? null : password // Null nếu không đổi password
                );
                
                staffService.updateStaff(updateStaff);
                JOptionPane.showMessageDialog(this,
                        "Cập nhật nhân viên thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            
            isConfirmed = true;
            this.dispose();
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Mức lương không hợp lệ.",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Đã có lỗi xảy ra: " + ex.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            logger.severe("Lỗi khi lưu nhân viên: " + ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSave1MouseClicked

    public boolean isConfirmed() {
        return isConfirmed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Khai báo các biến components ở đây
    // ===================================================================
    // GIỮ NGUYÊN PHẦN KHAI BÁO BIẾN ĐƯỢC GENERATE BỞI NETBEANS
    // ===================================================================
    private javax.swing.JButton btnSave1;
    private javax.swing.JComboBox<String> cboRole;
    private com.toedter.calendar.JDateChooser dateChooserBirthDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
