/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Panels.Roles;

import com.fat.BUS.Abstractions.Services.IRoleService;
import com.fat.BUS.Services.RoleService;
import com.fat.DAO.Repositories.RoleDAO;
import com.fat.DTO.Roles.RoleDTO;
import com.fat.GUI.Dialogs.Roles.AddOrUpdateRole;
import com.fat.GUI.Dialogs.Roles.PermissionRoleDialog;
import com.fat.GUI.Utils.ImageRenderer;
import com.formdev.flatlaf.FlatClientProperties;
import org.apache.poi.ss.usermodel.HorizontalAlignment;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author User
 */
public class RolesPanel extends javax.swing.JPanel {
    private final IRoleService roleService = RoleService.getInstance();
    /**
     * Creates new form RolesPanel
     */
    public RolesPanel() {
        initComponents();
        setCss();

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
              new Thread(() -> {
                  SwingUtilities.invokeLater(() -> {
                      loadData();
                      setCursor(Cursor.getDefaultCursor());
                  });
              }).start();
            }
        });
    }

    private void setCss() {
        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tên nhóm quyền");
    }

    private void loadData() {
        List<RoleDTO> roles = roleService.getAllRoles();
        fillTable(roles);
    }
    private void fillTable(List<RoleDTO> roles) {
        DefaultTableModel model = (DefaultTableModel) tblRole.getModel();
        model.setRowCount(0);
        for(var role : roles) {
            Object[] row = new Object[] {
                role.getId(),
                role.getName()
            };
            model.addRow(row);
        }
        DefaultTableCellRenderer centerRender = new DefaultTableCellRenderer();
        centerRender.setHorizontalAlignment(JLabel.CENTER);
       for(int i = 0; i < tblRole.getColumnCount(); i++) {
           tblRole.getColumnModel().getColumn(i).setCellRenderer(centerRender);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAuthorization = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRole = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Xbox Cross.png"))); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Close.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        btnUpdate.setText("Chỉnh sửa");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnReset.setBackground(new java.awt.Color(141, 141, 141));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reset.png"))); // NOI18N
        btnReset.setText("Hoàn tác lọc");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel1.setText("Tên nhóm quyền");

        btnAuthorization.setBackground(new java.awt.Color(50, 77, 177));
        btnAuthorization.setForeground(new java.awt.Color(255, 255, 255));
        btnAuthorization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User Shield.png"))); // NOI18N
        btnAuthorization.setText("Phân quyền");
        btnAuthorization.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuthorization.addActionListener(this::btnAuthorizationActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addGap(141, 141, 141)
                        .addComponent(btnAuthorization)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(17, 17, 17)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN NHÓM QUYỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRole.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblRole);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        AddOrUpdateRole roleDialog = new AddOrUpdateRole(parentFrame, true, null);
        roleDialog.setLocationRelativeTo(parentFrame);
        roleDialog.setVisible(true);

        loadData();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblRole.getSelectedRow();
        if(selectedRow == -1 ) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm quyền để xóa", "Chưa chọn nhóm quyền", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object objectId = tblRole.getValueAt(selectedRow, 0);
        int roleId = Integer.parseInt(objectId.toString());
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhóm quyền này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if(confirm != JOptionPane.YES_OPTION)  {
            return;
        }

        roleService.deleteRole(roleId);
        JOptionPane.showMessageDialog(this, "Xóa nhóm quyền thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        loadData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblRole.getSelectedRow();
        if(selectedRow  == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm quyền để chỉnh sửa", "Chưa chọn nhóm quyền", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object objectId = tblRole.getValueAt(selectedRow, 0);
        int roleId = Integer.parseInt(objectId.toString());
        RoleDTO selectedRole = roleService.getRoleById(roleId);
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        AddOrUpdateRole roleDialog = new AddOrUpdateRole(parentFrame, true, selectedRole);
        roleDialog.setLocationRelativeTo(parentFrame);
        roleDialog.setVisible(true);

        loadData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSearch.setText("");
        loadData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String keyword = txtSearch.getText().trim();
            List<RoleDTO> roles = roleService.filterRoleByList(keyword);
            fillTable(roles);
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnAuthorizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorizationActionPerformed
        int selectedRow = tblRole.getSelectedRow();
        if(selectedRow == -1 ) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm quyền để phân quyền", "Chưa chọn nhóm quyền", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object objectId = tblRole.getValueAt(selectedRow, 0);
        int roleId = Integer.parseInt(objectId.toString());
        RoleDTO role = roleService.getRoleById(roleId);
        PermissionRoleDialog permissionDialog = new PermissionRoleDialog((Frame) SwingUtilities.getWindowAncestor(this), true, role);
        permissionDialog.setLocationRelativeTo(this);
        permissionDialog.setVisible(true);
    }//GEN-LAST:event_btnAuthorizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAuthorization;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRole;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
