/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Panels.Statistics;

import com.fat.BUS.Abstractions.Services.IStatisticService;
import com.fat.BUS.Services.StatisticService;
import com.fat.BUS.Utils.ExcelHelper;
import com.fat.DTO.Statistics.StockStatisticDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;

/**
 *
 * @author User
 */
public class InventoryStatisticPanel extends javax.swing.JPanel {
    private final IStatisticService statisticService = StatisticService.getInstance();
    /**
     * Creates new form InventoryStatistic
     */
    public InventoryStatisticPanel() {
        initComponents();
        dateFrom.setDate(new Date());
        dateTo.setDate(new Date());
        initTable(statisticService.getStockStatistic(dateFrom.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate(), dateTo.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSearchInventory = new javax.swing.JButton();
        btnExportExcelInventory = new javax.swing.JButton();
        dateTo = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 286));

        btnSearchInventory.setBackground(new java.awt.Color(51, 51, 51));
        btnSearchInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchInventory.setText("Thống kê");
        btnSearchInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInventory.addActionListener(this::btnSearchInventoryActionPerformed);

        btnExportExcelInventory.setBackground(new java.awt.Color(46, 125, 50));
        btnExportExcelInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnExportExcelInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Microsoft Excel.png"))); // NOI18N
        btnExportExcelInventory.setText("Xuất Excel");
        btnExportExcelInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcelInventory.addActionListener(this::btnExportExcelInventoryActionPerformed);

        jLabel3.setText("Đến ngày");

        jLabel2.setText("Từ ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExportExcelInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportExcelInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.WEST);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ SP", "TÊN SẢN PHẨM", "TỒN ĐẦU KỲ", "NHẬP TRONG KỲ", "XUẤT TRONG KỲ", "TỒN CUỐI KỲ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblInventory);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchInventoryActionPerformed
        LocalDate fromDate = dateFrom.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        LocalDate toDate = dateTo.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        if (fromDate.isAfter(toDate)) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được sau ngày kết thúc!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        initTable(statisticService.getStockStatistic(fromDate, toDate));
    }//GEN-LAST:event_btnSearchInventoryActionPerformed

    private void btnExportExcelInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelInventoryActionPerformed
        ExcelHelper.exportToExcel(tblInventory, "Báo cáo tồn kho", "Báo cáo tồn kho");
    }//GEN-LAST:event_btnExportExcelInventoryActionPerformed
    private void initTable(List<StockStatisticDTO> list) {
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        model.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
        int stt = 1;
        for (StockStatisticDTO dto : list) {
            Object[] row = new Object[]{
                    stt++,
                    dto.getProductId(),
                    dto.getProductName(),
                    dto.getInitialStock(),
                    dto.getImportedQuantity(),
                    dto.getExportedQuantity(),
                    dto.getFinalStock()
            };
            model.addRow(row);
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblInventory.getColumnCount(); i++) {
            tblInventory.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcelInventory;
    private javax.swing.JButton btnSearchInventory;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventory;
    // End of variables declaration//GEN-END:variables
}
