/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Components;

import com.fat.Contract.Shared.PagedResult;
import com.fat.GUI.Events.PaginationEventListener;

/**
 *
 * @author User
 */
public class PaginationPanel extends javax.swing.JPanel {
    private PaginationEventListener listener;
    private int currentPage = 1;
    private PagedResult<?> pagedResult;
    /**
     * Creates new form PaginationPanel
     */
    public PaginationPanel() {
        initComponents();
        cboPageSize.setSelectedIndex(0);

    }


    public void addPaginationEventListener(PaginationEventListener listener){
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cboPageSize = new javax.swing.JComboBox<>();
        lblPage = new javax.swing.JLabel();
        firstBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        lastBtn = new javax.swing.JButton();

        jLabel3.setText("Số mục mỗi trang");

        cboPageSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Trang", "25 Trang", "50 Trang", "100 Trang" }));
        cboPageSize.addActionListener(this::cboPageSizeActionPerformed);

        lblPage.setText("1 - 10 trên 11");

        firstBtn.setText("<<");
        firstBtn.addActionListener(this::firstBtnActionPerformed);

        prevBtn.setText("<");
        prevBtn.addActionListener(this::prevBtnActionPerformed);

        nextBtn.setText(">");
        nextBtn.addActionListener(this::nextBtnActionPerformed);

        lastBtn.setText(">>");
        lastBtn.addActionListener(this::lastBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPage)
                .addGap(26, 26, 26)
                .addComponent(firstBtn)
                .addGap(18, 18, 18)
                .addComponent(prevBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastBtn)
                    .addComponent(firstBtn)
                    .addComponent(cboPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPage)
                    .addComponent(prevBtn)
                    .addComponent(nextBtn)
                    .addComponent(jLabel3))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboPageSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPageSizeActionPerformed
        if(listener != null) {
            this.currentPage = 1;
            int pageSize = getSelectedPageSize();
            listener.onPageChanged(currentPage,pageSize);
        }
    }//GEN-LAST:event_cboPageSizeActionPerformed

    private void firstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBtnActionPerformed
        if(currentPage > 1 && listener != null) {
            listener.onPageChanged(1,getSelectedPageSize());
        }
    }//GEN-LAST:event_firstBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        if (currentPage > 1 && listener != null) {
            currentPage--;
            listener.onPageChanged(currentPage, getSelectedPageSize());
        }
    }//GEN-LAST:event_prevBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if (pagedResult != null && currentPage < pagedResult.getTotalPages() && listener != null) {
            currentPage++;
            listener.onPageChanged(currentPage, getSelectedPageSize());
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void lastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastBtnActionPerformed

        if (pagedResult != null && currentPage < pagedResult.getTotalPages() && listener != null) {
            currentPage = pagedResult.getTotalPages();
            listener.onPageChanged(currentPage, getSelectedPageSize());
        }
    }//GEN-LAST:event_lastBtnActionPerformed

    public void setPagedResult(PagedResult<?> pagedResult){
        this.pagedResult = pagedResult;
        this.currentPage = pagedResult.getPageIndex();

        int from = (currentPage - 1) * pagedResult.getPageSize() + 1;
        int to = Math.min(currentPage * pagedResult.getPageSize(), (int) pagedResult.getTotalItems());
        if (pagedResult.getTotalItems() == 0) {
            lblPage.setText("0 mục");
            from = 0;
        } else {
            lblPage.setText(from + " - " + to + " trên " + pagedResult.getTotalItems());
        }
        updateButtonState();
    }

    public void updateButtonState() {
        if(pagedResult == null) return;

        firstBtn.setEnabled(pagedResult.isHasPreviousPage());
        prevBtn.setEnabled(pagedResult.isHasPreviousPage());
        nextBtn.setEnabled(pagedResult.isHasNextPage());
        lastBtn.setEnabled(pagedResult.isHasNextPage());

    }


    private int getSelectedPageSize() {
        String selected = cboPageSize.getSelectedItem().toString();

        return Integer.parseInt(selected.split(" ")[0]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboPageSize;
    private javax.swing.JButton firstBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lastBtn;
    private javax.swing.JLabel lblPage;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    // End of variables declaration//GEN-END:variables
}
