/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Dialogs.ConfirmDialog;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;

import java.awt.*;

import javax.swing.*;

import net.miginfocom.swing.MigLayout;

public class ConfirmDialog extends javax.swing.JDialog {
    private boolean confirmed = false;

    // Constructor linh hoạt
    public ConfirmDialog(Frame parent, String header, String message, String confirmText) {

        super(parent, true);

        setUndecorated(true); // Bỏ viền Windows để làm bo góc hiện đại
        // "insets 30" tạo khoảng cách lề bên trong rất thoáng

        JPanel contentPanel = new JPanel(new MigLayout("fillx, insets 30", "[left]", "[]20[]30[]"));

        contentPanel.setBackground(Color.WHITE);

       

        // Style bo góc 20px và viền xám nhạt cho Dialog

        contentPanel.putClientProperty("FlatLaf.style", "arc: 50; border: 1,1,1,1,#E0E0E0");



        // 1. Header (Tiêu đề lớn)

        JLabel lblHeader = new JLabel(header);

        lblHeader.setFont(new Font("Segoe UI", Font.BOLD, 22));

       

        // 2. Message (Nội dung cảnh báo)

        JTextArea txtMessage = new JTextArea(message);

        txtMessage.setFont(new Font("Segoe UI", Font.PLAIN, 15));

        txtMessage.setForeground(new Color(120, 120, 120)); // Màu xám nhẹ cho nội dung

        txtMessage.setEditable(false);

        txtMessage.setFocusable(false);

        txtMessage.setWrapStyleWord(true);

        txtMessage.setLineWrap(true); // Tự động xuống dòng

        txtMessage.setBackground(Color.WHITE);



        // 3. Buttons (Nút bấm)

        JButton btnCancel = new JButton("Hủy");

        JButton btnConfirm = new JButton(confirmText);



        // Style nút Hủy (viền mảnh)

        btnCancel.putClientProperty("FlatLaf.style", "borderWidth: 1; focusWidth: 0; outline: #E0E0E0");

        btnCancel.setPreferredSize(new Dimension(120, 40));



        // Style nút Xác nhận (màu cam đặc trưng Figma)

        btnConfirm.setBackground(new Color(255, 128, 0));

        btnConfirm.setForeground(Color.WHITE);

        btnConfirm.putClientProperty("FlatLaf.style", "borderWidth: 0; focusWidth: 0");

        btnConfirm.setPreferredSize(new Dimension(120, 40));

        btnConfirm.setCursor(new Cursor(Cursor.HAND_CURSOR));



        // Sự kiện nút bấm

        btnCancel.addActionListener(e -> dispose());

        btnConfirm.addActionListener(e -> {

            confirmed = true;

            dispose();

        });



        // Thêm các thành phần vào Layout

        contentPanel.add(lblHeader, "wrap");

        contentPanel.add(txtMessage, "growx, w 350!, wrap"); // Rộng tối đa 350px

       

        JPanel pnlButtons = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 0));

        pnlButtons.setOpaque(false);

        pnlButtons.add(btnCancel);

        pnlButtons.add(btnConfirm);

        contentPanel.add(pnlButtons, "growx");



        add(contentPanel);

        pack(); // Tự động co giãn theo nội dung

        setLocationRelativeTo(parent);

    }  /**
     * Creates new form ConfirmDialog
     */
    public ConfirmDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean isConfirmed() {
        return confirmed;
    }

    // Hàm tiện ích để gọi nhanh từ các Form khác
    public static boolean show(Frame parent, String header, String message, String confirmText) {
        ConfirmDialog dialog = new ConfirmDialog(parent, header, message, confirmText);
        dialog.setVisible(true);
        return dialog.isConfirmed();
    }
    
    public static void main(String[] args) {
        // 1. Kích hoạt giao diện FlatLaf
        FlatLightLaf.setup();

        // 2. Tạo một Frame cha giả (Hidden)
        JFrame dummyFrame = new JFrame();
        dummyFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dummyFrame.setSize(400, 400);
        dummyFrame.setLocationRelativeTo(null);
        // dummyFrame.setVisible(true); // Bạn có thể hiện lên hoặc ẩn đi tùy ý

        // 3. Gọi thử Dialog
        boolean result = ConfirmDialog.show(dummyFrame, 
            "Xóa vai trò", 
            "Bạn có chắc chắn muốn xóa \"vai trò\"? Hành động này không thể hoàn tác.", 
            "Xóa"
        );

        // 4. Kiểm tra kết quả
        if (result) {
            System.out.println("Kết quả: Người dùng đã bấm XÓA");
        } else {
            System.out.println("Kết quả: Người dùng đã bấm HỦY hoặc tắt Dialog");
        }

        // Thoát sau khi test xong
        System.exit(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
