/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fat.GUI;

import com.fat.DI.AppModule;
import com.fat.GUI.Panels.Products.ProductsPanel;
import com.fat.GUI.Panels.Staffs.StaffsPanel;
import com.fat.GUI.Panels.Supplier.SupplierPanel;
import com.fat.GUI.Utils.GlobalExceptionHandler;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Provider;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());
    private final Provider<ProductsPanel> productsPanelProvider;
    /**
     * Creates new form MainForm
     */
    @Inject
    public MainForm(Provider<ProductsPanel> productsPanelProvider) {
        this.productsPanelProvider = productsPanelProvider;
        initComponents();
        
//        tbtnTrangChu.putClientProperty("JButton.buttonType", "toolBarButton");
        UIManager.put("ToggleButton.selectedBackground", new Color(0, 120, 215)); // Màu xanh dương
        UIManager.put("ToggleButton.selectedForeground", Color.WHITE); // Chữ trắng


        // 2. CẤU HÌNH TOÀN CỤC CHO JTABLE (Và các thành phần khác)
        // ---------------------------------------------------

        // Chỉnh chiều cao hàng (Mặc định 16 rất bé, 30-35 là đẹp)
        UIManager.put("Table.rowHeight", 35);
        // Chỉnh Font chữ mặc định cho nội dung bảng
        UIManager.put("Table.font", new Font("Segoe UI", Font.PLAIN, 14));

        // Chỉnh Font chữ cho tiêu đề cột (Header) - Cần to và đậm hơn
        UIManager.put("TableHeader.font", new Font("Segoe UI", Font.BOLD, 14));
        UIManager.put("TableHeader.height", 40); // Chiều cao header
        UIManager.put("TableHeader.bottomSeparatorColor", new Color(220, 220, 220)); // Màu đường kẻ dưới header
        UIManager.put("TableHeader.foreground", new Color(121,121,121));

        // Hiệu ứng Zebra (Sọc vằn): Dòng chẵn lẻ khác màu nhau cho dễ nhìn
        UIManager.put("Table.alternateRowColor", new Color(242, 242, 242));

        // Ẩn đường kẻ dọc, chỉ hiện đường kẻ ngang (Style hiện đại)
        UIManager.put("Table.showVerticalLines", false);
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.gridColor", new Color(230, 230, 230)); // Màu đường kẻ nhạt thôi

        // Màu nền khi chọn 1 dòng (Selection)
        UIManager.put("Table.selectionBackground", new Color(50, 150, 255)); // Xanh dương
        UIManager.put("Table.selectionForeground", Color.WHITE); // Chữ trắng

        // Padding (Khoảng cách) nội dung trong ô cho đỡ dính lề
        UIManager.put("Table.cellNoFocusBorder", new EmptyBorder(0, 10, 0, 10));
        UIManager.put("Table.focusCellHighlightBorder", new EmptyBorder(0, 10, 0, 10));


        UIManager.put("Button.arc", 10);
        UIManager.put("Component.arc", 10); // Áp dụng cho TextField, ComboBox, Spinner...
        UIManager.put("ProgressBar.arc", 10);
        UIManager.put("TextComponent.arc", 10);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidebarPandel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        tbtnTrangChu = new javax.swing.JToggleButton();
        tbtnSelling = new javax.swing.JToggleButton();
        tbtnReceipt = new javax.swing.JToggleButton();
        tbtnCategory = new javax.swing.JToggleButton();
        tbtnProduct = new javax.swing.JToggleButton();
        tbtnImport = new javax.swing.JToggleButton();
        tbtnSupplier = new javax.swing.JToggleButton();
        tbtnPromotion = new javax.swing.JToggleButton();
        tbtnCustomer = new javax.swing.JToggleButton();
        tbtnStaff = new javax.swing.JToggleButton();
        tbtnRole = new javax.swing.JToggleButton();
        tbtnStatistic = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý bán tạp hóa");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 0));

        sidebarPandel.setBackground(new java.awt.Color(217, 217, 217));
        sidebarPandel.setPreferredSize(new java.awt.Dimension(200, 787));
        sidebarPandel.setLayout(new javax.swing.BoxLayout(sidebarPandel, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/StockTake.png"))); // NOI18N
        jLabel3.setText("Apolo");
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(32767, 80));
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 100));
        sidebarPandel.add(jLabel3);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        sidebarPandel.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        jLabel1.setText("Fat");
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 60));
        sidebarPandel.add(jLabel1);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setToolTipText("");
        sidebarPandel.add(jSeparator3);

        tbtnTrangChu.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnTrangChu);
        tbtnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Warehouse.png"))); // NOI18N
        tbtnTrangChu.setText("TRANG CHỦ");
        tbtnTrangChu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnTrangChu.setBorderPainted(false);
        tbtnTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnTrangChu.setIconTextGap(10);
        tbtnTrangChu.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnTrangChu.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnTrangChu.addActionListener(this::tbtnTrangChuActionPerformed);
        sidebarPandel.add(tbtnTrangChu);

        tbtnSelling.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnSelling);
        tbtnSelling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnSelling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Get Cash.png"))); // NOI18N
        tbtnSelling.setText("BÁN HÀNG");
        tbtnSelling.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnSelling.setBorderPainted(false);
        tbtnSelling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnSelling.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnSelling.setIconTextGap(10);
        tbtnSelling.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnSelling.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnSelling.addActionListener(this::tbtnSellingActionPerformed);
        sidebarPandel.add(tbtnSelling);

        tbtnReceipt.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnReceipt);
        tbtnReceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Order.png"))); // NOI18N
        tbtnReceipt.setText("HÓA ĐƠN");
        tbtnReceipt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnReceipt.setBorderPainted(false);
        tbtnReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnReceipt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnReceipt.setIconTextGap(10);
        tbtnReceipt.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnReceipt.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnReceipt.addActionListener(this::tbtnReceiptActionPerformed);
        sidebarPandel.add(tbtnReceipt);

        tbtnCategory.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnCategory);
        tbtnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Category.png"))); // NOI18N
        tbtnCategory.setText("DANH MỤC");
        tbtnCategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnCategory.setBorderPainted(false);
        tbtnCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnCategory.setIconTextGap(10);
        tbtnCategory.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnCategory.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnCategory.addActionListener(this::tbtnCategoryActionPerformed);
        sidebarPandel.add(tbtnCategory);

        tbtnProduct.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnProduct);
        tbtnProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Product.png"))); // NOI18N
        tbtnProduct.setText("SẢN PHẨM");
        tbtnProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnProduct.setBorderPainted(false);
        tbtnProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnProduct.setIconTextGap(10);
        tbtnProduct.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnProduct.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnProduct.addActionListener(this::tbtnProductActionPerformed);
        sidebarPandel.add(tbtnProduct);

        tbtnImport.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnImport);
        tbtnImport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Import.png"))); // NOI18N
        tbtnImport.setText("PHIẾU NHẬP");
        tbtnImport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnImport.setBorderPainted(false);
        tbtnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnImport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnImport.setIconTextGap(10);
        tbtnImport.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnImport.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnImport.addActionListener(this::tbtnImportActionPerformed);
        sidebarPandel.add(tbtnImport);

        tbtnSupplier.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnSupplier);
        tbtnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Supplier.png"))); // NOI18N
        tbtnSupplier.setText("NHÀ CUNG CẤP");
        tbtnSupplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnSupplier.setBorderPainted(false);
        tbtnSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnSupplier.setIconTextGap(10);
        tbtnSupplier.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnSupplier.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnSupplier.addActionListener(this::tbtnSupplierActionPerformed);
        sidebarPandel.add(tbtnSupplier);

        tbtnPromotion.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnPromotion);
        tbtnPromotion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnPromotion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Discount.png"))); // NOI18N
        tbtnPromotion.setText("KHUYẾN MÃI");
        tbtnPromotion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnPromotion.setBorderPainted(false);
        tbtnPromotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnPromotion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnPromotion.setIconTextGap(10);
        tbtnPromotion.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnPromotion.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnPromotion.addActionListener(this::tbtnPromotionActionPerformed);
        sidebarPandel.add(tbtnPromotion);

        tbtnCustomer.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnCustomer);
        tbtnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Customer.png"))); // NOI18N
        tbtnCustomer.setText("KHÁCH HÀNG");
        tbtnCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnCustomer.setBorderPainted(false);
        tbtnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnCustomer.setIconTextGap(10);
        tbtnCustomer.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnCustomer.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnCustomer.addActionListener(this::tbtnCustomerActionPerformed);
        sidebarPandel.add(tbtnCustomer);

        tbtnStaff.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnStaff);
        tbtnStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Staff.png"))); // NOI18N
        tbtnStaff.setText("NHÂN VIÊN");
        tbtnStaff.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnStaff.setBorderPainted(false);
        tbtnStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnStaff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnStaff.setIconTextGap(10);
        tbtnStaff.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnStaff.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnStaff.addActionListener(this::tbtnStaffActionPerformed);
        sidebarPandel.add(tbtnStaff);

        tbtnRole.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnRole);
        tbtnRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Role.png"))); // NOI18N
        tbtnRole.setText("NHÓM QUYỀN");
        tbtnRole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnRole.setBorderPainted(false);
        tbtnRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnRole.setIconTextGap(10);
        tbtnRole.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnRole.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnRole.addActionListener(this::tbtnRoleActionPerformed);
        sidebarPandel.add(tbtnRole);

        tbtnStatistic.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(tbtnStatistic);
        tbtnStatistic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Warehouse.png"))); // NOI18N
        tbtnStatistic.setText("THỐNG KÊ");
        tbtnStatistic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tbtnStatistic.setBorderPainted(false);
        tbtnStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbtnStatistic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtnStatistic.setIconTextGap(10);
        tbtnStatistic.setMaximumSize(new java.awt.Dimension(32767, 60));
        tbtnStatistic.setPreferredSize(new java.awt.Dimension(210, 100));
        tbtnStatistic.addActionListener(this::tbtnStatisticActionPerformed);
        sidebarPandel.add(tbtnStatistic);

        jButton1.setBackground(new java.awt.Color(134, 134, 134));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng xuất");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(300, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        sidebarPandel.add(jButton1);

        getContentPane().add(sidebarPandel, java.awt.BorderLayout.WEST);

        mainContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        mainContentPanel.setPreferredSize(new java.awt.Dimension(1000, 723));
        mainContentPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnImportActionPerformed

    private void tbtnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnCategoryActionPerformed

    private void tbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnReceiptActionPerformed

    private void tbtnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnProductActionPerformed

        if (mainContentPanel.getComponentCount() > 0 &&
            mainContentPanel.getComponent(0) instanceof ProductsPanel) {
            return; // Không làm gì cả, thoát hàm
        }
        ProductsPanel pPanel = productsPanelProvider.get();
        mainContentPanel.removeAll();
        mainContentPanel.add(pPanel);

        mainContentPanel.revalidate(); // Tính toán lại bố cục (Layout)
        mainContentPanel.repaint();
    }//GEN-LAST:event_tbtnProductActionPerformed

    private void tbtnSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSellingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnSellingActionPerformed

    private void tbtnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnTrangChuActionPerformed

    private void tbtnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSupplierActionPerformed
          if (mainContentPanel.getComponentCount() > 0 &&
            mainContentPanel.getComponent(0) instanceof SupplierPanel) {
            return; // Không làm gì cả, thoát hàm
        }
        SupplierPanel pPanel = new SupplierPanel();
        mainContentPanel.removeAll();
        mainContentPanel.add(pPanel);

        mainContentPanel.revalidate(); // Tính toán lại bố cục (Layout)
        mainContentPanel.repaint();
    }//GEN-LAST:event_tbtnSupplierActionPerformed

    private void tbtnPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnPromotionActionPerformed

    private void tbtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnCustomerActionPerformed

    private void tbtnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnStaffActionPerformed
        if (mainContentPanel.getComponentCount() > 0 &&
            mainContentPanel.getComponent(0) instanceof StaffsPanel) {
            return; // Không làm gì cả, thoát hàm
        }
        StaffsPanel pPanel = new StaffsPanel();
        mainContentPanel.removeAll();
        mainContentPanel.add(pPanel);

        mainContentPanel.revalidate(); // Tính toán lại bố cục (Layout)
        mainContentPanel.repaint();
    }//GEN-LAST:event_tbtnStaffActionPerformed

    private void tbtnRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnRoleActionPerformed

    private void tbtnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnStatisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnStatisticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 14));
        FlatLightLaf.setup();
        Thread.setDefaultUncaughtExceptionHandler(new GlobalExceptionHandler());
        // Khởi tạo Guice Injector
        Injector injector = Guice.createInjector(new AppModule());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainForm mainForm = injector.getInstance(MainForm.class);
            mainForm.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel sidebarPandel;
    private javax.swing.JToggleButton tbtnCategory;
    private javax.swing.JToggleButton tbtnCustomer;
    private javax.swing.JToggleButton tbtnImport;
    private javax.swing.JToggleButton tbtnProduct;
    private javax.swing.JToggleButton tbtnPromotion;
    private javax.swing.JToggleButton tbtnReceipt;
    private javax.swing.JToggleButton tbtnRole;
    private javax.swing.JToggleButton tbtnSelling;
    private javax.swing.JToggleButton tbtnStaff;
    private javax.swing.JToggleButton tbtnStatistic;
    private javax.swing.JToggleButton tbtnSupplier;
    private javax.swing.JToggleButton tbtnTrangChu;
    // End of variables declaration//GEN-END:variables
}
