/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fat.GUI.Dialogs.Roles;

import com.fat.BUS.Abstractions.Services.IRoleService;
import com.fat.BUS.Services.RoleService;
import com.fat.Contract.Constants.Action;
import com.fat.Contract.Constants.Function;
import com.fat.Contract.Constants.Permission;
import com.fat.DTO.Roles.RoleClaimDTO;
import com.fat.DTO.Roles.RoleDTO;
import com.fat.GUI.Utils.CheckboxRenderer;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author User
 */
public class PermissionRoleDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PermissionRoleDialog.class.getName());
    private List<String> functions;
    private final IRoleService roleService = RoleService.getInstance();
    private RoleDTO role;
    /**
     * Creates new form PermissionRole
     */
    public PermissionRoleDialog(java.awt.Frame parent, boolean modal, RoleDTO role) {
        super(parent, modal);
        this.role = role;
        initComponents();

        functions = new ArrayList<>();
        functions.add(Function.SELL);
        functions.add(Function.RECEIPT);
        functions.add(Function.CATEGORY);
        functions.add(Function.PRODUCT);
        functions.add(Function.IMPORT);
        functions.add(Function.SUPPLIER);
        functions.add(Function.PROMOTION);
        functions.add(Function.CUSTOMER);
        functions.add(Function.STAFF);
        functions.add(Function.ROLE);
        functions.add(Function.STATISTIC);

        lblTitle.setText("" + role.getName());

        setCss();
        initTable();
    }

    private void initTable() {
        Object[] header = new Object[] {
                "TÊN CHỨC NĂNG",
                "XEM",
                "THÊM",
                "XÓA",
                "SỬA",
        };
        // Override isCellEditable để chặn click vào ô null (ô bị ẩn)
        DefaultTableModel model = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Cột 0 (Tên) không sửa được
                if (column == 0) return false;
                // Lấy giá trị tại ô đó
                Object value = getValueAt(row, column);
                // Nếu value là null (tức là ẩn) thì không cho edit
                return value != null;
            }

            // Định nghĩa kiểu dữ liệu cho cột để JTable tự chọn Editor mặc định
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class;
                return Boolean.class; // Các cột còn lại là Boolean
            }
        };
        tblPermission.setModel(model);

        Map<String, Integer> permissions = roleService.getRoleClaims(role.getId());

        for(String func : functions) {
            int mask = permissions.getOrDefault(func, 0);
            int supportedMask = Permission.getPermission(func);
            Object canRead = ((supportedMask & Action.READ) != 0) ? ((mask & Action.READ) != 0) : null;
            Object canCreate = ((supportedMask & Action.CREATE) != 0) ? ((mask & Action.CREATE) != 0) : null;
            Object canDelete = ((supportedMask & Action.DELETE) != 0) ? ((mask & Action.DELETE) != 0) : null;
            Object canUpdate = ((supportedMask & Action.UPDATE) != 0) ?  ((mask & Action.UPDATE) != 0) : null;
            model.addRow(new Object[] {
                    func,
                    canRead,
                    canCreate,
                    canDelete,
                    canUpdate,
            });
        }


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblPermission.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        for(int i = 1; i < model.getColumnCount(); i++) {
            tblPermission.getColumnModel().getColumn(i).setCellRenderer(new CheckboxRenderer());
        }
    }

    private void setCss() {
        tblPermission.setSelectionBackground(Color.WHITE);
        tblPermission.setSelectionForeground(Color.BLACK);
        tblPermission.setForeground(Color.BLACK);
        tblPermission.setShowGrid(false);
        tblPermission.setBackground(Color.WHITE);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPermission = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Admin");

        btnSave.setBackground(new java.awt.Color(51, 51, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(this::btnSaveActionPerformed);

        tblPermission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPermission.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPermission);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPermission.getModel();
        List<RoleClaimDTO> permissions = new ArrayList<>();
        for (int row = 0; row < model.getRowCount(); row++) {
            String function = (String) model.getValueAt(row, 0);
            int permissionValue = 0;
            Object canReadObj = model.getValueAt(row, 1);
            Object canCreateObj = model.getValueAt(row, 2);
            Object canDeleteObj = model.getValueAt(row, 3);
            Object canUpdateObj = model.getValueAt(row, 4);
            if ((Boolean) canReadObj != null && (Boolean) canReadObj) {
                permissionValue |= Action.READ;
            }
            if ((Boolean) canCreateObj != null && (Boolean) canCreateObj) {
                permissionValue |= Action.CREATE;

            }
            if ((Boolean) canDeleteObj != null && (Boolean) canDeleteObj) {
                permissionValue |= Action.DELETE;
            }
            if ((Boolean) canUpdateObj != null && (Boolean) canUpdateObj) {
                permissionValue |= Action.UPDATE;
            }
            RoleClaimDTO dto = new RoleClaimDTO(
                    null,
                    role.getId(),
                    function,
                    permissionValue
            );
            permissions.add(dto);
        }
        roleService.setRoleClaims(role.getId(), permissions);
        JOptionPane.showMessageDialog(this, "Cập nhật quyền thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPermission;
    // End of variables declaration//GEN-END:variables
}
