/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Panels.Receipt;

import com.fat.BUS.Abstractions.Services.*;
import com.fat.BUS.Services.*;
import com.fat.Contract.Exceptions.ValidationException;
import com.fat.DTO.Categories.CategoryDTO;
import com.fat.DTO.Customers.CustomerDTO;
import com.fat.DTO.Products.ProductDTO;
import com.fat.DTO.Receipts.ReceiptDTO;
import com.fat.DTO.Receipts.ReceiptDetailDTO;
import com.fat.DTO.Staffs.StaffDTO;
import com.fat.DTO.Auths.UserSessionDTO;
import com.fat.GUI.Dialogs.Receipt.CustomersSelectionDialog;
import com.fat.GUI.Utils.FormatterUtil;
import com.formdev.flatlaf.FlatClientProperties;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tranc
 */
public class AddOrUpdateReceiptPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddOrUpdateReceiptPanel
     */
    private IReceiptService receiptService;
    private IProductService productService;
    private ICategoryService categoryService;
    private ICustomerService customerService;
    private IStaffService staffService;
    private IPromotionService promotionService;

    private CustomerDTO selectedCustomer = null;
    private StaffDTO currentStaff = null;

    private List<ProductDTO> allProducts = new ArrayList<>();
    private List<ReceiptDetailDTO> receiptDetails = new ArrayList<>();

    private Integer selectedCategoryId = null;
    private ProductDTO selectedProduct = null;
    private ReceiptDetailDTO selectedDetail = null;
    
    public AddOrUpdateReceiptPanel() {
        initComponents();
        receiptService = ReceiptService.getInstance();
        productService = ProductService.getInstance();
        categoryService = CategoryService.getInstance();
        customerService = CustomerService.getInstance();
        staffService = StaffService.getInstance();
        promotionService = PromotionService.getInstance();
        
        initTables();
        setCss();
        loadCategories();
        loadProducts();
        initReceiptInfo();
        setupTableListeners();
        
        // Listener cho button Tạo hóa đơn
        jButton2.addActionListener(this::jButton2ActionPerformed);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtImportID4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImportID5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtImportID6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTotalMoney = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtProductId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtImportPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        cboCategory1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtImportPrice1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtImportID4.setEditable(false);
        txtImportID4.addActionListener(this::txtImportID4ActionPerformed);

        jLabel10.setText("Mã hóa đơn");

        txtImportID5.setEditable(false);
        txtImportID5.addActionListener(this::txtImportID5ActionPerformed);

        jLabel11.setText("Nhân viên tạo hóa đơn");

        txtImportID6.setEditable(false);
        txtImportID6.addActionListener(this::txtImportID6ActionPerformed);

        jLabel12.setText("Khách hàng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tổng tiền");

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Ellipsis.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lblTotalMoney.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalMoney.setForeground(new java.awt.Color(255, 0, 51));
        lblTotalMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalMoney.setText("1000000000");

        jButton2.setBackground(new java.awt.Color(0, 178, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tạo phiếu nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(txtImportID5, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(txtImportID4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtImportID6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImportID4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImportID5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImportID6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalMoney))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "TÊN SẢN PHẨM", "TỒN KHO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TÊN SẢN PHẨM", "GIÁ BÁN", "SỐ LƯỢNG", "GIẢM GIÁ", "THÀNH TIỀN"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Xbox Cross.png"))); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Close.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        btnUpdate.setText("Chỉnh sửa");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        txtProductId.setEditable(false);
        txtProductId.addActionListener(this::txtProductIdActionPerformed);

        jLabel6.setText("Mã sản phẩm");

        txtProductName.setEditable(false);
        txtProductName.addActionListener(this::txtProductNameActionPerformed);

        jLabel7.setText("Tên sản phẩm");

        txtImportPrice.setEditable(false);
        txtImportPrice.addActionListener(this::txtImportPriceActionPerformed);

        jLabel8.setText("GIá bán");

        txtQuantity.setEditable(false);
        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.addActionListener(this::txtQuantityActionPerformed);

        jLabel9.setText("Số lượng");

        btnReset1.setBackground(new java.awt.Color(141, 141, 141));
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reset.png"))); // NOI18N
        btnReset1.setText("Hoàn tác lọc");
        btnReset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset1.addActionListener(this::btnReset1ActionPerformed);

        cboCategory1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboCategory1.addActionListener(this::cboCategory1ActionPerformed);

        jLabel3.setText("Danh mục sản phẩm");

        txtSearch1.addActionListener(this::txtSearch1ActionPerformed);
        txtSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearch1KeyPressed(evt);
            }
        });

        jLabel4.setText("Tên sản phẩm");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtImportPrice1.setEditable(false);
        txtImportPrice1.addActionListener(this::txtImportPrice1ActionPerformed);

        jLabel13.setText("Giảm giá");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cboCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnReset1))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6)
                                                .addComponent(txtProductId, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                .addComponent(txtImportPrice))
                                            .addComponent(jLabel8))
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtImportPrice1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImportPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(62, 62, 62)))
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImportPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initTables() {
        // ===== Table 1: Danh sách sản phẩm =====
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        model1.setRowCount(0);
        String[] headers1 = {"ID", "TÊN SẢN PHẨM", "TỒN KHO"};
        model1.setColumnIdentifiers(headers1);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // ===== Table 2: Chi tiết hóa đơn =====
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        model2.setRowCount(0);
        String[] headers2 = {"ID", "TÊN SẢN PHẨM", "GIÁ BÁN", "SỐ LƯỢNG", "GIẢM GIÁ", "THÀNH TIỀN"};
        model2.setColumnIdentifiers(headers2);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        jTable2.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        jTable2.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void setCss() {
        txtSearch1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tìm sản phẩm...");
        txtQuantity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập số lượng");
        
        // Giá bán và giảm giá là readonly (tự động tính)
        txtProductId.setEditable(false);
        txtProductName.setEditable(false);
        txtImportPrice.setEditable(false);  // Giá bán - readonly
        txtImportPrice1.setEditable(false); // Giảm giá - readonly
        txtQuantity.setEditable(true);      // Chỉ số lượng được nhập
    }
    
    private void setupTableListeners() {
        // Listener cho jTable1 (sản phẩm): Khi click chọn sản phẩm
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    int productId = (int) jTable1.getValueAt(row, 0);
                    selectedProduct = allProducts.stream()
                        .filter(p -> p.getId().equals(productId))
                        .findFirst()
                        .orElse(null);
                    
                    if (selectedProduct != null) {
                        showProductInfo(selectedProduct);
                    }
                }
            }
        });
        
        // Listener cho jTable2 (chi tiết): Khi click chọn detail
        jTable2.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = jTable2.getSelectedRow();
                if (row >= 0) {
                    int productId = (int) jTable2.getValueAt(row, 0);
                    selectedDetail = receiptDetails.stream()
                        .filter(d -> d.getProductId().equals(productId))
                        .findFirst()
                        .orElse(null);
                    
                    if (selectedDetail != null) {
                        loadDetailToInput(selectedDetail);
                    }
                }
            }
        });
        
        // Double click trên jTable1 để focus vào nhập số lượng
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0) {
                        txtQuantity.requestFocus();
                    }
                }
            }
        });
    }
    
    private void loadCategories() {
        DefaultComboBoxModel<CategoryDTO> model = new DefaultComboBoxModel<>();
        model.addElement(new CategoryDTO(0, "Tất cả"));
        
        List<CategoryDTO> categories = categoryService.getAllCategories();
        for (CategoryDTO cat : categories) {
            model.addElement(cat);
        }
        
        cboCategory1.setModel(model);
        cboCategory1.setSelectedIndex(0);
        
        cboCategory1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, 
                                                         int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof CategoryDTO) {
                    setText(((CategoryDTO) value).getName());
                }
                return this;
            }
        });
    }
    
    private void loadProducts() {
        String keyword = txtSearch1.getText().trim();
        
        List<ProductDTO> products = productService.getAllProducts();
        
        // Filter theo category
        if (selectedCategoryId != null && selectedCategoryId != 0) {
            products = products.stream()
                .filter(p -> p.getCategoryId().equals(selectedCategoryId))
                .toList();
        }
        
        // Filter theo keyword
        if (!keyword.isBlank()) {
            products = products.stream()
                .filter(p -> p.getName().toLowerCase().contains(keyword.toLowerCase()))
                .toList();
        }
        
        // Chỉ hiện sản phẩm còn tồn kho
        products = products.stream()
            .filter(p -> p.getStock() != null && p.getStock() > 0)
            .toList();
        
        allProducts = products;
        fillProductTable(products);
    }
    
    private void fillProductTable(List<ProductDTO> products) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (ProductDTO p : products) {
            model.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getStock()
            });
        }
    }
    
    private void initReceiptInfo() {
        // Generate mã hóa đơn tự động: HD + timestamp
        String receiptCode = "HD" + System.currentTimeMillis();
        txtImportID4.setText(receiptCode);
        
        // Lấy thông tin staff hiện tại từ session
        UserSessionDTO session = UserSessionDTO.getInstance();
        if (session.getStaffId() != null) {
            currentStaff = staffService.getStaffById(session.getStaffId());
        }
        if (currentStaff == null) {
            // Fallback nếu chưa login
            currentStaff = staffService.getStaffById(1);
        }
        if (currentStaff != null) {
            txtImportID5.setText(currentStaff.getFirstName() + " " + currentStaff.getLastName());
        }
        
        // Chưa chọn khách hàng
        txtImportID6.setText("");
        
        // Tổng tiền = 0
        updateTotalMoney();
    }
    
    private void showProductInfo(ProductDTO product) {
        txtProductId.setText(String.valueOf(product.getId()));
        txtProductName.setText(product.getName());
        // Hiển thị giá bán
        txtImportPrice.setText(product.getPrice() != null ? product.getPrice().toString() : "0");
        // Tính và hiển thị giảm giá
        BigDecimal discountAmount = promotionService.calculateDiscountPrice(product.getId(), product.getPrice());
        txtImportPrice1.setText(discountAmount.toString());
        txtQuantity.setText("");
        txtQuantity.requestFocus();
    }
    
    private void loadDetailToInput(ReceiptDetailDTO detail) {
        ProductDTO product = productService.getProductById(detail.getProductId());
        if (product != null) {
            txtProductId.setText(String.valueOf(product.getId()));
            txtProductName.setText(product.getName());
            txtImportPrice.setText(detail.getPrice().toString());
        }
        txtImportPrice1.setText(detail.getDiscountAmount() != null ? detail.getDiscountAmount().toString() : "0");
        txtQuantity.setText(String.valueOf(detail.getQuantity()));
    }
    
    private void fillDetailTable() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        for (ReceiptDetailDTO detail : receiptDetails) {
            ProductDTO product = productService.getProductById(detail.getProductId());
            String productName = product != null ? product.getName() : "N/A";
            
            model.addRow(new Object[]{
                detail.getProductId(),
                productName,
                FormatterUtil.toVND(detail.getPrice()),
                detail.getQuantity(),
                FormatterUtil.toVND(detail.getDiscountAmount()),
                FormatterUtil.toVND(detail.getSubTotalAmount())
            });
        }
    }
    
    private void updateTotalMoney() {
        BigDecimal total = receiptDetails.stream()
            .map(ReceiptDetailDTO::getSubTotalAmount)
            .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        lblTotalMoney.setText(FormatterUtil.toVND(total));
    }
    
    private void clearInput() {
        txtProductId.setText("");
        txtProductName.setText("");
        txtImportPrice.setText("");
        txtImportPrice1.setText("");
        txtQuantity.setText("");
        selectedProduct = null;
        selectedDetail = null;
    }
    
    private void resetForm() {
        receiptDetails.clear();
        fillDetailTable();
        
        selectedCustomer = null;
        txtImportID6.setText("");
        
        String receiptCode = "HD" + System.currentTimeMillis();
        txtImportID4.setText(receiptCode);
        
        clearInput();
        updateTotalMoney();
        
        jTable1.clearSelection();
        jTable2.clearSelection();
    }
    private void txtImportID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportID4ActionPerformed

    private void txtImportID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportID5ActionPerformed

    private void txtImportID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportID6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Window window = SwingUtilities.getWindowAncestor(this);
            JFrame parentFrame = null;
            
            if (window instanceof JFrame) {
                parentFrame = (JFrame) window;
            }
            
            CustomersSelectionDialog dialog = new CustomersSelectionDialog(parentFrame, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            
            if (dialog.isConfirmed()) {
                selectedCustomer = dialog.getSelectedCustomer();
                if (selectedCustomer != null) {
                    txtImportID6.setText(selectedCustomer.getFullName());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Lỗi khi mở dialog chọn khách hàng: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (selectedProduct == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String qtyStr = txtQuantity.getText().trim();
            
            if (qtyStr.isBlank()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int quantity = Integer.parseInt(qtyStr);
            
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Kiểm tra tồn kho
            if (selectedProduct.getStock() != null && quantity > selectedProduct.getStock()) {
                JOptionPane.showMessageDialog(this, "Số lượng vượt quá tồn kho (" + selectedProduct.getStock() + ")", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Check trùng sản phẩm
            boolean exists = receiptDetails.stream()
                .anyMatch(d -> d.getProductId().equals(selectedProduct.getId()));
            
            if (exists) {
                JOptionPane.showMessageDialog(this, "Sản phẩm đã có trong danh sách", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Lấy giá bán và giảm giá
            BigDecimal price = selectedProduct.getPrice();
            BigDecimal discountAmount = promotionService.calculateDiscountPrice(selectedProduct.getId(), price);
            // Thành tiền = (Giá bán - Giảm giá) * Số lượng
            BigDecimal subTotal = price.subtract(discountAmount).multiply(new BigDecimal(quantity));
            
            // Tạo detail mới
            ReceiptDetailDTO detail = new ReceiptDetailDTO();
            detail.setProductId(selectedProduct.getId());
            detail.setQuantity(quantity);
            detail.setPrice(price);
            detail.setDiscountAmount(discountAmount);
            detail.setSubTotalAmount(subTotal);
            
            receiptDetails.add(detail);
            fillDetailTable();
            updateTotalMoney();
            clearInput();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedDetail == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc muốn xóa sản phẩm này?", 
            "Xác nhận", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            receiptDetails.removeIf(d -> d.getProductId().equals(selectedDetail.getProductId()));
            fillDetailTable();
            updateTotalMoney();
            clearInput();
            selectedDetail = null;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (selectedDetail == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String qtyStr = txtQuantity.getText().trim();
            
            if (qtyStr.isBlank()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int quantity = Integer.parseInt(qtyStr);
            
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Kiểm tra tồn kho
            ProductDTO product = productService.getProductById(selectedDetail.getProductId());
            if (product != null && product.getStock() != null && quantity > product.getStock()) {
                JOptionPane.showMessageDialog(this, "Số lượng vượt quá tồn kho (" + product.getStock() + ")", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Update detail
            selectedDetail.setQuantity(quantity);
            BigDecimal subTotal = selectedDetail.getPrice().subtract(
                selectedDetail.getDiscountAmount() != null ? selectedDetail.getDiscountAmount() : BigDecimal.ZERO
            ).multiply(new BigDecimal(quantity));
            selectedDetail.setSubTotalAmount(subTotal);
            
            fillDetailTable();
            updateTotalMoney();
            clearInput();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtImportPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        txtSearch1.setText("");
        cboCategory1.setSelectedIndex(0);
        selectedCategoryId = null;
        loadProducts();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void cboCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategory1ActionPerformed
        CategoryDTO selected = (CategoryDTO) cboCategory1.getSelectedItem();
        if (selected != null) {
            selectedCategoryId = selected.getId();
            loadProducts();
        }
    }//GEN-LAST:event_cboCategory1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtSearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            loadProducts();
        }
    }//GEN-LAST:event_txtSearch1KeyPressed

    private void txtImportPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportPrice1ActionPerformed

    // Event: Tạo hóa đơn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (receiptDetails.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hóa đơn phải có ít nhất 1 sản phẩm", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Tạo ReceiptDTO
            ReceiptDTO dto = new ReceiptDTO();
            dto.setCode(txtImportID4.getText());
            dto.setCustomerId(selectedCustomer != null ? selectedCustomer.getId() : null);
            dto.setStaffId(currentStaff.getId());
            dto.setReceiptItems(new ArrayList<>(receiptDetails));
            
            // Tính tổng tiền
            BigDecimal subTotal = receiptDetails.stream()
                .map(d -> d.getPrice().multiply(new BigDecimal(d.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            BigDecimal totalDiscount = receiptDetails.stream()
                .map(d -> d.getDiscountAmount() != null ? d.getDiscountAmount().multiply(new BigDecimal(d.getQuantity())) : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            BigDecimal totalAmount = receiptDetails.stream()
                .map(ReceiptDetailDTO::getSubTotalAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            dto.setSubTotalAmount(subTotal);
            dto.setTotalDiscountAmount(totalDiscount);
            dto.setTotalAmount(totalAmount);
            
            receiptService.createReceipt(dto);
            JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            // Navigate back to ReceiptPanel
            navigateToReceiptPanel();
            
        } catch (ValidationException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi validation", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    // Navigate back to ReceiptPanel
    private void navigateToReceiptPanel() {
        Container parent = this.getParent();
        while (parent != null && !(parent.getLayout() instanceof CardLayout)) {
            parent = parent.getParent();
        }
        
        if (parent != null && parent.getLayout() instanceof CardLayout) {
            CardLayout cardLayout = (CardLayout) parent.getLayout();
            
            // Find ReceiptPanel and refresh
            Component[] components = parent.getComponents();
            for (Component comp : components) {
                if (comp instanceof ReceiptPanel) {
                    ((ReceiptPanel) comp).loadData();
                    break;
                }
            }
            
            // Remove current panel
            parent.remove(this);
            
            // Show ReceiptPanel
            try {
                cardLayout.show(parent, "RECEIPT");
            } catch (Exception e) {
                cardLayout.first(parent);
            }
            
            parent.revalidate();
            parent.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboCategory1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblTotalMoney;
    private javax.swing.JTextField txtImportID4;
    private javax.swing.JTextField txtImportID5;
    private javax.swing.JTextField txtImportID6;
    private javax.swing.JTextField txtImportPrice;
    private javax.swing.JTextField txtImportPrice1;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
