/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fat.GUI.Panels.Receipt;

import com.fat.BUS.Abstractions.Services.ICustomerService;
import com.fat.BUS.Abstractions.Services.IProductService;
import com.fat.BUS.Abstractions.Services.IReceiptService;
import com.fat.BUS.Abstractions.Services.IStaffService;
import com.fat.BUS.Services.CustomerService;
import com.fat.BUS.Services.ProductService;
import com.fat.BUS.Services.ReceiptService;
import com.fat.BUS.Services.StaffService;
import com.fat.BUS.Utils.ExcelHelper;
import com.fat.Contract.Enumerations.ReceiptSort;
import com.fat.Contract.Enumerations.SortOrder;
import com.fat.DTO.Customers.CustomerDTO;
import com.fat.DTO.Products.ProductDTO;
import com.fat.DTO.Receipts.ReceiptDTO;
import com.fat.DTO.Receipts.ReceiptDetailDTO;
import com.fat.DTO.Staffs.StaffDTO;
import com.fat.GUI.Utils.FormatterUtil;
import com.formdev.flatlaf.FlatClientProperties;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author pc
 */
public class ReceiptPanel extends javax.swing.JPanel {

    private IReceiptService receiptService;
    private ICustomerService customerService;
    private IStaffService staffService;
    private IProductService productService;
    
    private List<ReceiptDTO> currentList = new ArrayList<>();
    private ReceiptDTO selectedReceipt = null;

    /**
     * Creates new form ReceiptPanel
     */
    public ReceiptPanel() {
        initComponents();
        
        this.setName("ReceiptPanel");
        
        receiptService = ReceiptService.getInstance();
        customerService = CustomerService.getInstance();
        staffService = StaffService.getInstance();
        productService = ProductService.getInstance();
        
        initTables();
        setCss();
        
        // Table selection listener
        setupTableListener();
        
        // Load initial data
        loadFilters();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtImportID = new javax.swing.JTextField();
        txtCreateDate = new javax.swing.JTextField();
        txtStaff = new javax.swing.JTextField();
        txtSupplier = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtTotal1 = new javax.swing.JTextField();
        txtTotal2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtFromDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtToDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboSupplier1 = new javax.swing.JComboBox<>();
        cboSupplier2 = new javax.swing.JComboBox<>();
        txtSearch1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ HÓA ĐƠN", "KHÁCH HÀNG", "TỔNG THANH TOÁN"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtImportID.setEditable(false);
        txtImportID.setText("jTextField1");
        txtImportID.addActionListener(this::txtImportIDActionPerformed);

        txtCreateDate.setEditable(false);
        txtCreateDate.setText("jTextField1");

        txtStaff.setEditable(false);
        txtStaff.setText("jTextField1");

        txtSupplier.setEditable(false);
        txtSupplier.setText("jTextField1");

        txtStatus.setEditable(false);
        txtStatus.setText("jTextField1");

        txtTotal.setEditable(false);
        txtTotal.setText("jTextField1");

        jLabel6.setText("Mã Hóa Đơn");

        jLabel7.setText("Ngày tạo");

        jLabel8.setText("Nhân viên");

        jLabel9.setText("Khách Hàng");

        jLabel10.setText("SĐT");

        jLabel11.setText("Tổng Giá Trị");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TÊN SP", "SỐ LƯỢNG", "GIÁ BÁN", "GIẢM GIÁ", "THÀNH TIỀN"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        txtTotal1.setEditable(false);
        txtTotal1.setText("jTextField1");
        txtTotal1.addActionListener(this::txtTotal1ActionPerformed);

        txtTotal2.setEditable(false);
        txtTotal2.setText("jTextField1");

        jLabel15.setText("SĐT");

        jLabel16.setText("SĐT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtImportID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCreateDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImportID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnReset.setBackground(new java.awt.Color(141, 141, 141));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reset.png"))); // NOI18N
        btnReset.setText("Hoàn tác lọc");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel1.setText("Mã phiếu nhập");

        jLabel2.setText("Sắp Xếp Theo");

        btnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        btnUpdate.setText("In Hóa Đơn");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnExportExcel.setBackground(new java.awt.Color(46, 125, 50));
        btnExportExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Microsoft Excel.png"))); // NOI18N
        btnExportExcel.setText("Xuất Excel");
        btnExportExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcel.addActionListener(this::btnExportExcelActionPerformed);

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Xbox Cross.png"))); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(this::btnAddActionPerformed);

        jLabel5.setText("Ngày tạo");

        jLabel12.setText("Từ ngày");

        jLabel13.setText("Đến ngày");

        jLabel14.setText("-");

        cboSupplier1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboSupplier1.addActionListener(this::cboSupplier1ActionPerformed);

        cboSupplier2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboSupplier2.addActionListener(this::cboSupplier2ActionPerformed);

        txtSearch1.addActionListener(this::txtSearch1ActionPerformed);
        txtSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearch1KeyPressed(evt);
            }
        });

        jLabel3.setText("Nhân viên bán");

        jLabel4.setText("Tổng thanh toán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExportExcel)
                    .addComponent(btnUpdate))
                .addGap(666, 666, 666))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(304, 304, 304)
                    .addComponent(cboSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1189, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtToDate, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(cboSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initTables() {
        // ===== Table 1: Danh sách hóa đơn =====
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        model1.setRowCount(0);
        String[] headers1 = {"MÃ HÓA ĐƠN", "KHÁCH HÀNG", "TỔNG THANH TOÁN"};
        model1.setColumnIdentifiers(headers1);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // ===== Table 2: Chi tiết hóa đơn =====
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        model2.setRowCount(0);
        String[] headers2 = {"ID", "TÊN SP", "SỐ LƯỢNG", "GIÁ BÁN", "GIẢM GIÁ", "THÀNH TIỀN"};
        model2.setColumnIdentifiers(headers2);
        
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        jTable2.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        jTable2.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
    }
    
    private void setCss() {
        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tìm kiếm mã hóa đơn...");
        txtSearch1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tổng thanh toán...");
        
        txtImportID.setEditable(false);
        txtCreateDate.setEditable(false);
        txtStaff.setEditable(false);
        txtSupplier.setEditable(false);
        txtStatus.setEditable(false);
        txtTotal.setEditable(false);
        txtTotal1.setEditable(false);
        txtTotal2.setEditable(false);
        
        // Clear default text
        txtImportID.setText("");
        txtCreateDate.setText("");
        txtStaff.setText("");
        txtSupplier.setText("");
        txtStatus.setText("");
        txtTotal.setText("");
        txtTotal1.setText("");
        txtTotal2.setText("");
        
        // Fix label text (GEN có tên Import cũ)
        jLabel1.setText("Mã hóa đơn");
        jLabel3.setText("Thứ tự");
        jLabel15.setText("Tổng giảm giá");
        jLabel16.setText("Tổng thanh toán");
    }
    
    private void setupTableListener() {
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    String receiptCode = (String) jTable1.getValueAt(row, 0);
                    selectedReceipt = currentList.stream()
                        .filter(r -> r.getCode().equals(receiptCode))
                        .findFirst()
                        .orElse(null);
                    
                    if (selectedReceipt != null) {
                        showReceiptDetails(selectedReceipt);
                    }
                }
            }
        });
    }
    
    private void loadFilters() {
        // ===== Load sort options (cboSupplier1) =====
        DefaultComboBoxModel<String> sortModel = new DefaultComboBoxModel<>();
        sortModel.addElement("Ngày tạo");
        sortModel.addElement("Tổng thanh toán");
        cboSupplier1.setModel(sortModel);
        
        // ===== Load sort order (cboSupplier2) =====
        DefaultComboBoxModel<String> orderModel = new DefaultComboBoxModel<>();
        orderModel.addElement("Giảm dần");
        orderModel.addElement("Tăng dần");
        cboSupplier2.setModel(orderModel);
    }
    
    public void loadData() {
        try {
            String keyword = txtSearch.getText().trim();
            
            // Get dates
            LocalDateTime from = null;
            if (txtFromDate.getDate() != null) {
                from = txtFromDate.getDate().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime()
                    .withHour(0).withMinute(0).withSecond(0);
            }
            
            LocalDateTime to = null;
            if (txtToDate.getDate() != null) {
                to = txtToDate.getDate().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime()
                    .withHour(23).withMinute(59).withSecond(59);
            }
            
            // Get total amount filter
            BigDecimal totalAmount = null;
            String totalStr = txtSearch1.getText().trim();
            if (!totalStr.isBlank()) {
                try {
                    totalAmount = new java.math.BigDecimal(totalStr);
                } catch (NumberFormatException ex) {
                    // Ignore invalid number
                }
            }
            
            // Get sort
            ReceiptSort sortBy = ReceiptSort.DATE;
            String sortStr = (String) cboSupplier1.getSelectedItem();
            if ("Tổng thanh toán".equals(sortStr)) {
                sortBy = ReceiptSort.TOTAL_AMOUNT;
            }
            
            SortOrder sortOrder = SortOrder.DESCENDING;
            String orderStr = (String) cboSupplier2.getSelectedItem();
            if ("Tăng dần".equals(orderStr)) {
                sortOrder = SortOrder.ASCENDING;
            }
            
            // Filter
            currentList = receiptService.filterReceiptByList(
                keyword.isBlank() ? null : keyword,
                from, to, null, totalAmount,
                sortOrder, sortBy
            );
            
            // Clear selection and details
            selectedReceipt = null;
            clearDetailView();
            
            fillTable(currentList);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Lỗi load dữ liệu: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void fillTable(List<ReceiptDTO> receipts) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (ReceiptDTO receipt : receipts) {
            // Lấy tên khách hàng
            String customerName = "Khách lẻ";
            if (receipt.getCustomerId() != null) {
                try {
                    CustomerDTO customer = customerService.getCustomerById(receipt.getCustomerId());
                    if (customer != null) {
                        customerName = customer.getFullName();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            
            model.addRow(new Object[]{
                receipt.getCode(),
                customerName,
                FormatterUtil.toVND(receipt.getTotalAmount())
            });
        }
    }
    
    private void showReceiptDetails(ReceiptDTO receipt) {
        // Load full details from DAO (cache doesn't have receiptItems)
        ReceiptDTO fullReceipt = receiptService.getReceiptById(receipt.getId());
        if (fullReceipt == null) return;
        
        // Fill text fields
        txtImportID.setText(fullReceipt.getCode());
        txtCreateDate.setText(FormatterUtil.toDateTime(fullReceipt.getCreatedAt()));
        
        // Staff
        try {
            StaffDTO staff = staffService.getStaffById(fullReceipt.getStaffId());
            txtStaff.setText(staff != null ? staff.getFirstName() + " " + staff.getLastName() : "N/A");
        } catch (Exception e) {
            txtStaff.setText("N/A");
        }
        
        // Customer
        if (fullReceipt.getCustomerId() != null) {
            try {
                CustomerDTO customer = customerService.getCustomerById(fullReceipt.getCustomerId());
                if (customer != null) {
                    txtSupplier.setText(customer.getFullName());
                    txtStatus.setText(customer.getPhoneNumber() != null ? customer.getPhoneNumber() : "N/A");
                } else {
                    txtSupplier.setText("Khách lẻ");
                    txtStatus.setText("");
                }
            } catch (Exception e) {
                txtSupplier.setText("Khách lẻ");
                txtStatus.setText("");
            }
        } else {
            txtSupplier.setText("Khách lẻ");
            txtStatus.setText("");
        }
        
        // Totals
        txtTotal.setText(FormatterUtil.toVND(fullReceipt.getSubTotalAmount()));
        txtTotal1.setText(FormatterUtil.toVND(fullReceipt.getTotalDiscountAmount()));
        txtTotal2.setText(FormatterUtil.toVND(fullReceipt.getTotalAmount()));
        
        // Fill details table
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        if (fullReceipt.getReceiptItems() != null) {
            for (ReceiptDetailDTO detail : fullReceipt.getReceiptItems()) {
                // Lấy tên sản phẩm
                String productName = "N/A";
                try {
                    ProductDTO product = productService.getProductById(detail.getProductId());
                    if (product != null) {
                        productName = product.getName();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                model.addRow(new Object[]{
                    detail.getProductId(),
                    productName,
                    detail.getQuantity(),
                    FormatterUtil.toVND(detail.getPrice()),
                    FormatterUtil.toVND(detail.getDiscountAmount()),
                    FormatterUtil.toVND(detail.getSubTotalAmount())
                });
            }
        }
    }
    
    private void clearDetailView() {
        txtImportID.setText("");
        txtCreateDate.setText("");
        txtStaff.setText("");
        txtSupplier.setText("");
        txtStatus.setText("");
        txtTotal.setText("");
        txtTotal1.setText("");
        txtTotal2.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        selectedReceipt = null;
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSearch.setText("");
        txtSearch1.setText("");
        cboSupplier1.setSelectedIndex(0);
        cboSupplier2.setSelectedIndex(0);
        txtFromDate.setDate(null);
        txtToDate.setDate(null);
        loadData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            loadData();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // In hóa đơn - chức năng mở rộng
        if (selectedReceipt == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn", "Chưa chọn", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Chức năng in hóa đơn đang phát triển", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        try {
            JTable exportTable = new JTable();
            DefaultTableModel model = (DefaultTableModel) exportTable.getModel();
            
            String[] columns = {"STT", "MÃ HÓA ĐƠN", "KHÁCH HÀNG", "TỔNG THANH TOÁN", "NGÀY TẠO", "NHÂN VIÊN"};
            model.setColumnIdentifiers(columns);
            
            List<ReceiptDTO> exportsData = currentList.isEmpty() ?
                receiptService.getAllReceipts() : currentList;
            
            int stt = 1;
            for (ReceiptDTO r : exportsData) {
                String customerName = "Khách lẻ";
                if (r.getCustomerId() != null) {
                    try {
                        CustomerDTO c = customerService.getCustomerById(r.getCustomerId());
                        if (c != null) customerName = c.getFullName();
                    } catch (Exception e) { /* keep default */ }
                }
                
                String staffName = "N/A";
                try {
                    StaffDTO staff = staffService.getStaffById(r.getStaffId());
                    if (staff != null) staffName = staff.getFirstName() + " " + staff.getLastName();
                } catch (Exception e) { /* keep default */ }
                
                model.addRow(new Object[]{
                    stt++,
                    r.getCode(),
                    customerName,
                    FormatterUtil.toVND(r.getTotalAmount()),
                    FormatterUtil.toDateTime(r.getCreatedAt()),
                    staffName
                });
            }
            
            ExcelHelper.exportToExcel(exportTable, "Danh_sach_hoa_don", "Danh sách hóa đơn");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xuất Excel: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Navigate to AddOrUpdateReceiptPanel
        Container parent = this.getParent();
        while (parent != null && !(parent.getLayout() instanceof CardLayout)) {
            parent = parent.getParent();
        }
        
        if (parent != null && parent.getLayout() instanceof CardLayout) {
            CardLayout cardLayout = (CardLayout) parent.getLayout();
            
            // Remove old panel if exists
            Component[] components = parent.getComponents();
            for (Component comp : components) {
                if (comp.getName() != null && comp.getName().equals("AddReceiptPanel")) {
                    parent.remove(comp);
                }
            }
            
            AddOrUpdateReceiptPanel panel = new AddOrUpdateReceiptPanel();
            panel.setName("AddReceiptPanel");
            parent.add(panel, "AddReceiptPanel");
            cardLayout.show(parent, "AddReceiptPanel");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtImportIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportIDActionPerformed

    private void txtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal1ActionPerformed

    private void cboSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSupplier1ActionPerformed
        loadData();
    }//GEN-LAST:event_cboSupplier1ActionPerformed

    private void cboSupplier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSupplier2ActionPerformed
        loadData();
    }//GEN-LAST:event_cboSupplier2ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        loadData();
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtSearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch1KeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            loadData();
        }
    }//GEN-LAST:event_txtSearch1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboSupplier1;
    private javax.swing.JComboBox<String> cboSupplier2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCreateDate;
    private com.toedter.calendar.JDateChooser txtFromDate;
    private javax.swing.JTextField txtImportID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtStaff;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSupplier;
    private com.toedter.calendar.JDateChooser txtToDate;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotal2;
    // End of variables declaration//GEN-END:variables
}
