/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fat.GUI.Dialogs.Staffs;

import com.fat.BUS.Abstractions.Services.IRoleService;
import com.fat.BUS.Abstractions.Services.IStaffService;
import com.fat.BUS.Services.RoleService;
import com.fat.BUS.Services.StaffService;
import com.fat.BUS.Utils.ValidatorUtil;
import com.fat.Contract.Exceptions.DuplicateStaffUserNameException;
import com.fat.Contract.Exceptions.ValidationException;
import com.fat.DTO.Roles.RoleDTO;
import com.fat.DTO.Staffs.StaffDTO;
import com.formdev.flatlaf.FlatClientProperties;

import javax.swing.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author GIGABYTE
 */
public class AddOrUpdateStaffDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddOrUpdateStaffDialog.class.getName());


    private IStaffService staffService = StaffService.getInstance();
    private IRoleService roleService = RoleService.getInstance();
    private StaffDTO staffDTO = null;
    private boolean isConfirmed = false;
    
    /**
     * Creates new form AddOrUpdateStaffDialog
     */
    public AddOrUpdateStaffDialog(java.awt.Frame parent, boolean modal, StaffDTO staffDTO) {
        super(parent, modal);
        initComponents();
        loadRoles();
        setCss();
        
        this.staffDTO = staffDTO;
        initStaffDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnSave1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(255, 158, 106));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtLastName.addActionListener(this::txtLastNameActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        jLabel2.setText("Họ ");

        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);

        jLabel3.setText("Tên");

        cboRole.addActionListener(this::cboRoleActionPerformed);

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Số điện thoại");

        jLabel8.setText("Mức lương");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setText("Tên đăng nhập");

        jLabel10.setText("Mật khẩu");

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Thiết lập vai trò");

        jLabel12.setText("Vai trò");

        btnSave1.setBackground(new java.awt.Color(255, 158, 106));
        btnSave1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(255, 255, 255));
        btnSave1.setText("Lưu");
        btnSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSave1MouseClicked(evt);
            }
        });
        btnSave1.addActionListener(this::btnSave1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseClicked
        try {
            // 1. Lấy dữ liệu từ form
            String firstName = txtFirstName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String phoneNumber = txtPhoneNumber.getText().trim();
            String userName = txtUserName.getText().trim();
            String password = txtPassword.getText().trim();
            String salaryText = txtSalary.getText().trim();
            Date birthDateObj = jDateChooser1.getDate();
            RoleDTO selectedRole = (RoleDTO) cboRole.getSelectedItem();
            
            // 2. Parse và validate dữ liệu
            BigDecimal salary = null;
            if (!salaryText.isEmpty()) {
                salary = new BigDecimal(salaryText);
            }
            
            LocalDate birthDate = null;
            if (birthDateObj != null) {
                birthDate = birthDateObj.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
            }
            
            Integer roleId = selectedRole != null ? selectedRole.getId() : null;
            
            // 3. Tạo DTO và gọi service
            if (staffDTO == null) {
                // CREATE - Truyền password gốc, service sẽ mã hóa
                // Validate password không trống cho CREATE
                if (password.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Mật khẩu không được để trống khi tạo nhân viên mới!",
                            "Lỗi",
                            JOptionPane.ERROR_MESSAGE);
                    txtPassword.requestFocus();
                    return;
                }
                
                StaffDTO newStaff = new StaffDTO();
                newStaff.setFirstName(firstName);
                newStaff.setLastName(lastName);
                newStaff.setBirthday(birthDate);
                newStaff.setSalary(salary);
                newStaff.setPhoneNumber(phoneNumber);
                newStaff.setRoleId(roleId);
                newStaff.setCreatedAt(java.time.LocalDateTime.now());
                newStaff.setUserName(userName);
                newStaff.setPassword(password);
                
                ValidatorUtil.validate(newStaff);
                staffService.createStaff(newStaff);
                JOptionPane.showMessageDialog(this,
                        "Thêm nhân viên thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                // UPDATE - Truyền null hoặc password mới
                String passwordToUpdate = password.isEmpty() ? null : password;
                
                StaffDTO updateStaff = new StaffDTO();
                updateStaff.setId(staffDTO.getId());
                updateStaff.setFirstName(firstName);
                updateStaff.setLastName(lastName);
                updateStaff.setBirthday(birthDate);
                updateStaff.setSalary(salary);
                updateStaff.setPhoneNumber(phoneNumber);
                updateStaff.setRoleId(roleId);
                updateStaff.setCreatedAt(staffDTO.getCreatedAt());
                updateStaff.setUserName(userName);
                updateStaff.setPassword(passwordToUpdate);
                
                ValidatorUtil.validate(updateStaff);
                staffService.updateStaff(updateStaff);
                JOptionPane.showMessageDialog(this,
                        "Cập nhật nhân viên thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            
            isConfirmed = true;
            this.dispose();
            
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this,
                    "Mức lương không hợp lệ. Vui lòng nhập số!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            txtSalary.requestFocus();
        } catch (ValidationException validationException) {
            JOptionPane.showMessageDialog(this,
                    validationException.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } catch (DuplicateStaffUserNameException duplicateStaffUserNameException) {
            JOptionPane.showMessageDialog(this,
                    duplicateStaffUserNameException.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Đã có lỗi xảy ra khi lưu nhân viên.",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            logger.severe("Lỗi khi lưu nhân viên: " + ex);
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSave1MouseClicked

    private void cboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRoleActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void loadRoles() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboRole.getModel();
       // roleService.refreshCache();
        var roles = roleService.getAllRoles();

        for (var role : roles) {
            model.addElement(role);
        }

        // Chọn mặc định đầu tiên
        if (cboRole.getItemCount() > 0) {
            cboRole.setSelectedIndex(0);
        }
    }
    
    private void setCss() {
        btnSave1.putClientProperty(FlatClientProperties.STYLE, "arc: 10; borderWidth: 0;");
        txtFirstName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên");
        txtLastName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập họ");
        txtPhoneNumber.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập số điện thoại");
        txtUserName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập tên đăng nhập");
        txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mật khẩu (min 6 ký tự)");
        txtSalary.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mức lương");
    }
    
    private void initStaffDetail() {
        if (staffDTO != null) {
            setTitle("Cập nhật nhân viên");

            txtFirstName.setText(staffDTO.getFirstName());
            txtLastName.setText(staffDTO.getLastName());
            txtPhoneNumber.setText(staffDTO.getPhoneNumber());
            txtUserName.setText(staffDTO.getUserName());
            txtSalary.setText(staffDTO.getSalary().toString());

            // Chuyển LocalDate sang Date cho JDateChooser
            LocalDate birthDate = staffDTO.getBirthday();
            Date date = Date.from(birthDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
            jDateChooser1.setDate(date);

            // Chọn vai trò tương ứng
            for (int i = 0; i < cboRole.getItemCount(); i++) {
                RoleDTO role = (RoleDTO) cboRole.getItemAt(i);
                if (role.getId().equals(staffDTO.getRoleId())) {
                    cboRole.setSelectedIndex(i);
                    break;
                }
            }

            // Password để trống (không hiển thị hash)
            txtPassword.setText("");
            txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,
                    "Để trống nếu không đổi mật khẩu");
        } else {
            setTitle("Thêm nhân viên mới");
        }
    }
    
    public void setStaffDTO(StaffDTO staffDTO) {
        this.staffDTO = staffDTO;
    }
    
    public boolean isConfirmed() {
        return isConfirmed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JComboBox<RoleDTO> cboRole;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
